name: "Build and Push Docker Image"

on:
  workflow_call:
    inputs:
      app_name:
        description: "Name of the application"
        required: true
        type: string
      k8s_ns:
        description: "Kubernetes namespace"
        required: true
        type: string
      target_environment:
        description: "Name of the environment (e.g. staging, production)"
        required: true
        type: string
      dockerfile_path:
        description: "Path to the Dockerfile"
        required: false
        default: "./Dockerfile"
        type: string

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    environment: ${{ inputs.target_environment }}

    env:
      CLUSTER_NAME: ${{ inputs.target_environment == 'production' && 'use1-prod' || 'use1-stage' }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        run: |
          docker build \
            --push \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ inputs.app_name }}:${{ github.sha }} \
            -f "${{ inputs.dockerfile_path }}" \
            .
