name: Caller TruffleHog Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trigger_scan:
    uses: storyprotocol/gha-workflows/.github/workflows/reusable-secrets-scanning.yml@main
    with:
      branch: ${{ github.ref_name }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
