name: Test reusable slack notification workflow

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main

jobs:
  call-slack-notif:
    uses: cenevan/gha-workflows/.github/workflows/reusable-slack-notifs.yml@main
    with:
      short-desc: 'Test Description'
      title: 'Test Title'
      img-url: 'https://imgur.com/gallery/npm-install-OsbqxXW'
      img-alt-text: 'Test alt text'
      
      
